# -*- coding: utf-8 -*-
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VERSION_FILE = HERE / "version.txt"
OUTPUT_FILE = HERE / "version_info.txt"

# Everything below stays the same every build, regardless of version
COMPANY_NAME = "TDG"
FILE_DESCRIPTION = "A large multiuse RTM tool for Skate 3 on the PS3"
PRODUCT_NAME = "TDG's TMenu - Skate 3 RTM Tool"
LEGAL_COPYRIGHT = "TDG"
INTERNAL_NAME = "TMenu"
ORIGINAL_FILENAME = "TMenu.exe"

DEFAULT_VERSION = "0.15.1.0"

TEMPLATE = '''# UTF-8
#
# Auto-generated by build_version.py on every build - don't hand edit.
# Windows VERSIONINFO resource, embedded into the exe by PyInstaller's
# --version-file flag. Shows up under the exe's Properties > Details tab.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,      # VOS_NT_WINDOWS32
    fileType=0x1,    # VFT_APP
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',  # US English, Unicode
          [
            StringStruct(u'CompanyName', u'{company}'),
            StringStruct(u'FileDescription', u'{description}'),
            StringStruct(u'FileVersion', u'{dotted}'),
            StringStruct(u'InternalName', u'{internal_name}'),
            StringStruct(u'LegalCopyright', u'{copyright}'),
            StringStruct(u'OriginalFilename', u'{original_filename}'),
            StringStruct(u'ProductName', u"{product_name}"),
            StringStruct(u'ProductVersion', u'{dotted}'),
          ])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''


def load_current_version():
    # falls back to version.txt, or DEFAULT_VERSION if it doesn't exist yet
    if VERSION_FILE.exists():
        text = VERSION_FILE.read_text(encoding="utf-8").strip()
        if text:
            return text
    return DEFAULT_VERSION


def normalize(version_str):
    # turns "15.2", "15.2.0", "0.15.2.0" etc into a 4-int tuple, padding with zeros
    parts = [p for p in re.split(r"[.,]", version_str.strip()) if p != ""]
    if not parts:
        raise ValueError("Version number can't be blank.")
    nums = []
    for p in parts[:4]:
        if not p.isdigit():
            raise ValueError(
                f"'{version_str}' isn't a valid version number - use digits "
                f"separated by dots, e.g. 15.2.0"
            )
        nums.append(int(p))
    while len(nums) < 4:
        nums.append(0)
    return tuple(nums)


def main():
    user_input = sys.argv[1].strip() if len(sys.argv) > 1 else ""
    version_str = user_input if user_input else load_current_version()

    try:
        version_tuple = normalize(version_str)
    except ValueError as e:
        print(str(e))
        sys.exit(1)

    dotted = ".".join(str(n) for n in version_tuple)

    VERSION_FILE.write_text(dotted + "\n", encoding="utf-8")

    OUTPUT_FILE.write_text(
        TEMPLATE.format(
            version_tuple=version_tuple,
            company=COMPANY_NAME,
            description=FILE_DESCRIPTION,
            dotted=dotted,
            internal_name=INTERNAL_NAME,
            copyright=LEGAL_COPYRIGHT,
            original_filename=ORIGINAL_FILENAME,
            product_name=PRODUCT_NAME,
        ),
        encoding="utf-8",
    )
    print(f"Version set to {dotted}")

if __name__ == "__main__":
    main()
