# -*- coding: utf-8 -*-
"""
build_version.py
=================
Turns a version number into version_info.txt (the Windows VERSIONINFO
resource PyInstaller bakes into TMenu.exe via --version-file). build.bat
calls this every time it runs, passing along whatever the person typed at
its "Enter version number" prompt.

Company/description/product name/copyright are the constants below - they
stay the same every build regardless of what version number is entered.
Only the version tuples and the FileVersion/ProductVersion strings change.

Usage (from build.bat):
    python build_version.py "15.2.0"     -> writes that version, remembers it
    python build_version.py ""           -> keeps whatever version.txt has
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VERSION_FILE = HERE / "version.txt"
OUTPUT_FILE = HERE / "version_info.txt"

# --- Everything below stays the same every build, regardless of version ---
COMPANY_NAME = "TDG"
FILE_DESCRIPTION = "A large multiuse RTM tool for Skate 3 on the PS3"
PRODUCT_NAME = "TDG's TMenu - Skate 3 RTM Tool"
LEGAL_COPYRIGHT = "TDG"
INTERNAL_NAME = "TMenu"
ORIGINAL_FILENAME = "TMenu.exe"

DEFAULT_VERSION = "0.15.1.0"

TEMPLATE = '''# UTF-8
#
# version_info.txt
# =================
# AUTO-GENERATED by build_version.py every time build.bat runs - don't hand
# edit this file, it gets overwritten on the next build. To change the
# version number, just run build.bat and type a new one when it asks (or
# edit version.txt directly). To change the company/description/product
# name, edit the constants at the top of build_version.py instead.
#
# Windows VERSIONINFO resource, embedded into the exe by PyInstaller's
# --version-file flag. This is what shows up under the exe's Properties >
# Details tab in Windows Explorer.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,      # VOS_NT_WINDOWS32
    fileType=0x1,    # VFT_APP
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',  # US English, Unicode
          [
            StringStruct(u'CompanyName', u'{company}'),
            StringStruct(u'FileDescription', u'{description}'),
            StringStruct(u'FileVersion', u'{dotted}'),
            StringStruct(u'InternalName', u'{internal_name}'),
            StringStruct(u'LegalCopyright', u'{copyright}'),
            StringStruct(u'OriginalFilename', u'{original_filename}'),
            StringStruct(u'ProductName', u"{product_name}"),
            StringStruct(u'ProductVersion', u'{dotted}'),
          ])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''


def load_current_version():
    """Falls back to version.txt's last-used version, or DEFAULT_VERSION if
    version.txt doesn't exist yet (very first build)."""
    if VERSION_FILE.exists():
        text = VERSION_FILE.read_text(encoding="utf-8").strip()
        if text:
            return text
    return DEFAULT_VERSION


def normalize(version_str):
    """Turns "15.2", "15.2.0", "0.15.2.0", etc. into a 4-int tuple - pads
    with zeros if fewer than 4 parts were given, ignores anything past the
    4th part. Windows VERSIONINFO tuples are always exactly 4 numbers."""
    parts = [p for p in re.split(r"[.,]", version_str.strip()) if p != ""]
    if not parts:
        raise ValueError("Version number can't be blank.")
    nums = []
    for p in parts[:4]:
        if not p.isdigit():
            raise ValueError(
                f"'{version_str}' isn't a valid version number - use digits "
                f"separated by dots, e.g. 15.2.0"
            )
        nums.append(int(p))
    while len(nums) < 4:
        nums.append(0)
    return tuple(nums)


def main():
    user_input = sys.argv[1].strip() if len(sys.argv) > 1 else ""
    version_str = user_input if user_input else load_current_version()

    try:
        version_tuple = normalize(version_str)
    except ValueError as e:
        print(str(e))
        sys.exit(1)

    dotted = ".".join(str(n) for n in version_tuple)

    VERSION_FILE.write_text(dotted + "\n", encoding="utf-8")

    OUTPUT_FILE.write_text(
        TEMPLATE.format(
            version_tuple=version_tuple,
            company=COMPANY_NAME,
            description=FILE_DESCRIPTION,
            dotted=dotted,
            internal_name=INTERNAL_NAME,
            copyright=LEGAL_COPYRIGHT,
            original_filename=ORIGINAL_FILENAME,
            product_name=PRODUCT_NAME,
        ),
        encoding="utf-8",
    )
    print(f"Version set to {dotted}")


if __name__ == "__main__":
    main()
